### ISSUE TITLE
resolver errors on getItems in OpenAPI definition (HTML)

### ISSUE THREAD

**Issue by rkoblenzer** [ldproxy/ldproxy#1307]
### ldproxy Version

4.2.0

### Current Behavior

A red frame (wrapper) with errors shows up at the top of the OpenAPI definition (HTML) when I click on `getItems`: 

```
Errors
 
Resolver error at paths./collections/vineyards/items.get.responses.200.content.application/vnd.ogc.fg+json;compatibility=geojson.schema.properties.features.items.properties.geometry.$ref
Could not resolve reference: undefined undefined
Resolver error at paths./collections/vineyards/items.get.responses.200.content.application/vnd.ogc.fg+json;compatibility=geojson.schema.properties.timeStamp.$ref
Could not resolve reference: undefined undefined
Resolver error at paths./collections/vineyards/items.get.responses.200.content.application/vnd.ogc.fg+json;compatibility=geojson.schema.properties.numberMatched.$ref
Could not resolve reference: undefined undefined
Resolver error at paths./collections/vineyards/items.get.responses.200.content.application/vnd.ogc.fg+json;compatibility=geojson.schema.properties.numberReturned.$ref
Could not resolve reference: undefined undefined
```

The behaviour can also be reproduced with other deployments. 

It seems that the errors have no further negative impact (or I did not notice it yet).

### Expected Behavior

No errors occur.

### Steps to Reproduce

Open https://demo.ldproxy.net/vineyards/api?f=html#/Access%20data/vineyards.getItems and scroll to the top. A red wrapper with errors shows up.
 

### Relevant log output

```shell
From JS debug console: https://raw.githubusercontent.com/opengeospatial/ogcapi-features/master/core/openapi/ogcapi-features-1.yaml -> http 404.
```

**Comment by cportele** [comment]
The referenced document was no longer available in the OGC GitHub repository. I have recovered the document for backward compatibility. There should be no errors now.

**Comment by rkoblenzer** [comment]
Thanks! Indeed, the errors have disappeared.
